version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
