---
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - CSS_SCSS_LINT
  - JAVASCRIPT_ES
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
  - SPELL_MISSPELL
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
JSON_JSONLINT_ARGUMENTS: --comments
