name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions: read-all

jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn list
      - run: yarn build

      - run: |
          yarn lint
          if [ -n "$(git status --short)" ]; then
              git diff
              exit 1
          fi

      - run: yarn test

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [check-license-lines, build]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
